### ISSUE TITLE
Is `form_time` meant to be declared multifile?

### ISSUE THREAD

**Issue by shonfeder** [mndrix/julian#15]
In the tutorial it says

```
Fortunately, `form_time/2` is declared `multifile`.  The following should do the trick:
```

But I'm getting an override of a weak of import when I try to extent the predicate, and I don't see a `multifile` declaration when searching the code base here. Which should be fixed, the documentation or the library? I'm happy to make a PR to do the right thing :)

Wonderful library, btw! Thank you for picking up maintenance, @dvberkel!

**Comment by dvberkel** [comment]
@shonfeder Thanks for pointing this out.

I will have to take a look and determine a good course of actions. Once determined I would love for your contribution.

**Comment by shonfeder** [comment]
It turns out I was just having trouble using multifile predicates! So sorry fort the noise here. It's working as documented!

**Comment by dvberkel** [comment]
No need for sorry.

Exploring is a healthy habit that should be encouraged. At signal things that do not work for you can potentially discover a real problem. Or at least a gap in understanding.

I am happy that it it working for you
